### ISSUE TITLE
Upgrade to 4.0

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lora_gateway#6]
Is upgrading to lora_gateway 4.0 feasible? If so, can this be done, and if not, what's the plan?

I'm considering forking from the new lora_pkt_fwd and plug-in a new protocol based on MQTT to get rid of UDP and support authentication.

**Comment by kruisdraad** [comment]
+1 on upgrading, the latest version solves a bug that will hit from time to time:

ERROR: [up] bin_to_b64 failed line 1822

The amount of changes/commits done on the TTN repo seem very low, perhaps merge the commits?

**Comment by egourlao** [comment]
The question was closed, because deprecated - upgrading to 4.0.0 was accomplished, thanks to @devlaam's work.
